import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Ripple from "@/components/ui/ripple";
import DotPattern from "@/components/ui/dot-pattern";
import NavHeader from "@/components/ui/NavHeader";
import { ThemeProvider } from "next-themes";
import { ClientThemeProvider } from "@/components/ui/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientThemeProvider>
          {/* <DotPattern className="opacity-25" /> */}
          <NavHeader />
          <Ripple />
          {children}
        </ClientThemeProvider>
      </body>
    </html>
  );
}
